name: fx_user_ui
description: Configurable Flutter authentication UI backed by fx_user_core.
version: 0.0.1
homepage: https://github.com/TolyFx/fx
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  fx_user_core: ^0.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
