name: fx_ability
description: FrameworkX 客户端宿主能力注册与访问入口。
version: 0.1.0
homepage: https://github.com/TolyFx/fx
resolution: workspace

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
