name: fx_user_core
description: 面向 Fx 应用的用户认证领域模型与远端仓储契约。
version: 0.0.1
homepage: https://github.com/TolyFx/fx
resolution: workspace

environment:
  sdk: '>=3.12.0 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
