[package]
name = "fx_storage_router"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fx_storage_core = { path = "../../fx_storage_core" }
fx_storage_local = { path = "../fx_storage_local" }
fx_storage_oss = { path = "../fx_storage_oss" }

[lints]
workspace = true
