[workspace]
resolver = "3"
members = [
    "crates/admin/*",
    "crates/foundation/*",
    "crates/identity/auth/fx_auth_core",
    "crates/identity/auth/fx_auth_code",
    "crates/identity/auth/providers/*",
    "crates/identity/user/fx_user_core",
    "crates/identity/user/fx_user_service",
    "crates/identity/user/fx_user",
    "crates/identity/user/adapters/*",
    "crates/storage/fx_storage_core",
    "crates/storage/fx_storage_service",
    "crates/storage/backends/*",
    "crates/storage/adapters/*",
    "crates/storage/extensions/*",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/TolyFx/FrameworkX"

[workspace.dependencies]
axum = { version = "0.8", features = ["multipart"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
rand = "0.9"
argon2 = "0.5"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "9"
reqwest = { version = "0.12", features = ["json"] }
uuid = { version = "1", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.6", features = ["trace"] }

[workspace.lints.rust]
unsafe_code = "forbid"
