[package]
name = "fx_auth_google"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fx_auth_core = { path = "../../fx_auth_core" }
fx_core = { path = "../../../../foundation/fx_core" }
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
jsonwebtoken.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
