[package]
name = "fx_user_service"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fx_core = { path = "../../../foundation/fx_core" }
fx_auth_core = { path = "../../auth/fx_auth_core" }
fx_user_core = { path = "../fx_user_core" }
argon2.workspace = true
chrono.workspace = true

[lints]
workspace = true
